name: Despliegue Manual v2

on:
  workflow_dispatch:   # ← Activa el botón "Run workflow"

jobs:
  build:
    strategy:
      matrix:
        # Definimos una variable llamada 'sistema_operativo' (u 'os')
        # y le damos una lista de valores.
        sistema_operativo: [ubuntu-latest, windows-latest]

    # Aquí usamos la variable. GitHub creará 3 trabajos paralelos:
    # 1. runs-on: ubuntu-latest
    # 2. runs-on: windows-latest
    runs-on: ${{ matrix.sistema_operativo }}

    steps:
      # 1. Descargar el código
      - name: Descargar código
        uses: actions/checkout@v4

      # 2. Configurar Java 21
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: 'maven'

      # 3. Dar permisos al wrapper
      - name: Dar permisos al wrapper de Maven
        run: chmod +x mvnw

      # 4. Ejecutar Tests en cada sistema operativo
      - name: Ejecutar Tests en ${{ matrix.sistema_operativo }}
        run: mvn -B test